##This is hello world ci/cd pipeline script##

trigger:
  branches:
    include:
      - azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: echo "Hello World"
    displayName: Print Hello World
